version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydb"
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    container_name: streamlit
    depends_on:
      - backend
    environment:
      API_URL: "http://backend:8000"
    ports:
      - "8501:8501"

volumes:
  postgres_data:
